spring:
  application:
    name: users-service

server:
  port: 8095

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    preferIpAddress: true