spring:
  application:
    name: maps-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 8096

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true