spring:
  application:
    name: chats-service

server:
  port: 8097

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    preferIpAddress: true